version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8080:80"
    volumes:
      - ./apache:/var/www/html


  python_server:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "65432:65432"
    stdin_open: true
    tty: true

